pyhmmer.errors.UnexpectedError: Unexpected error occurred in 'p7_Builder': eslEFORMAT (status code 7), weird error with the  pytrimal obj that was converted to pyhmmer DigitalMSA. Seem exactly the same..